version: "3.7"
services: 
  mongo:
    image: 'mongo:4.2.3'
    container_name: 'mongodb'
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - tasklist-volume:/data/db
volumes: 
  tasklist-volume:
    driver: local